'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace serviciowebFlavio
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://servicioweb.com/miServicio", ConfigurationName:="serviciowebFlavio.serviciowebSoap")>  _
    Public Interface serviciowebSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://servicioweb.com/miServicio no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As serviciowebFlavio.HelloWorldRequest) As serviciowebFlavio.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As serviciowebFlavio.HelloWorldRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.HelloWorldResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CrearConsultaResult del espacio de nombres http://servicioweb.com/miServicio no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/CrearConsulta", ReplyAction:="*")>  _
        Function CrearConsulta(ByVal request As serviciowebFlavio.CrearConsultaRequest) As serviciowebFlavio.CrearConsultaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/CrearConsulta", ReplyAction:="*")>  _
        Function CrearConsultaAsync(ByVal request As serviciowebFlavio.CrearConsultaRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.CrearConsultaResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarUsuarioResult del espacio de nombres http://servicioweb.com/miServicio no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/SeleccionarUsuario", ReplyAction:="*")>  _
        Function SeleccionarUsuario(ByVal request As serviciowebFlavio.SeleccionarUsuarioRequest) As serviciowebFlavio.SeleccionarUsuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/SeleccionarUsuario", ReplyAction:="*")>  _
        Function SeleccionarUsuarioAsync(ByVal request As serviciowebFlavio.SeleccionarUsuarioRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.SeleccionarUsuarioResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://servicioweb.com/miServicio no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/crearUsuario", ReplyAction:="*")>  _
        Function crearUsuario(ByVal request As serviciowebFlavio.crearUsuarioRequest) As serviciowebFlavio.crearUsuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/crearUsuario", ReplyAction:="*")>  _
        Function crearUsuarioAsync(ByVal request As serviciowebFlavio.crearUsuarioRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.crearUsuarioResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EliminarUsuarioResult del espacio de nombres http://servicioweb.com/miServicio no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/EliminarUsuario", ReplyAction:="*")>  _
        Function EliminarUsuario(ByVal request As serviciowebFlavio.EliminarUsuarioRequest) As serviciowebFlavio.EliminarUsuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://servicioweb.com/miServicio/EliminarUsuario", ReplyAction:="*")>  _
        Function EliminarUsuarioAsync(ByVal request As serviciowebFlavio.EliminarUsuarioRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.EliminarUsuarioResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CrearConsultaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CrearConsulta", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.CrearConsultaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.CrearConsultaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class CrearConsultaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CrearConsultaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CrearConsultaResponse", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.CrearConsultaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.CrearConsultaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class CrearConsultaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CrearConsultaResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CrearConsultaResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.CrearConsultaResult = CrearConsultaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SeleccionarUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SeleccionarUsuario", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.SeleccionarUsuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.SeleccionarUsuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class SeleccionarUsuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SeleccionarUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SeleccionarUsuarioResponse", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.SeleccionarUsuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.SeleccionarUsuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class SeleccionarUsuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SeleccionarUsuarioResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SeleccionarUsuarioResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.SeleccionarUsuarioResult = SeleccionarUsuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class crearUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="crearUsuario", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.crearUsuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.crearUsuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class crearUsuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombre As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public contrasena As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombre As String, ByVal contrasena As String)
            MyBase.New
            Me.nombre = nombre
            Me.contrasena = contrasena
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class crearUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="crearUsuarioResponse", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.crearUsuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.crearUsuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class crearUsuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public crearUsuarioResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal crearUsuarioResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.crearUsuarioResult = crearUsuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EliminarUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EliminarUsuario", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.EliminarUsuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.EliminarUsuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class EliminarUsuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EliminarUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EliminarUsuarioResponse", [Namespace]:="http://servicioweb.com/miServicio", Order:=0)>  _
        Public Body As serviciowebFlavio.EliminarUsuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As serviciowebFlavio.EliminarUsuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://servicioweb.com/miServicio")>  _
    Partial Public Class EliminarUsuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EliminarUsuarioResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EliminarUsuarioResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.EliminarUsuarioResult = EliminarUsuarioResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface serviciowebSoapChannel
        Inherits serviciowebFlavio.serviciowebSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class serviciowebSoapClient
        Inherits System.ServiceModel.ClientBase(Of serviciowebFlavio.serviciowebSoap)
        Implements serviciowebFlavio.serviciowebSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_HelloWorld(ByVal request As serviciowebFlavio.HelloWorldRequest) As serviciowebFlavio.HelloWorldResponse Implements serviciowebFlavio.serviciowebSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As serviciowebFlavio.HelloWorldRequest = New serviciowebFlavio.HelloWorldRequest()
            inValue.Body = New serviciowebFlavio.HelloWorldRequestBody()
            Dim retVal As serviciowebFlavio.HelloWorldResponse = CType(Me,serviciowebFlavio.serviciowebSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_HelloWorldAsync(ByVal request As serviciowebFlavio.HelloWorldRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.HelloWorldResponse) Implements serviciowebFlavio.serviciowebSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of serviciowebFlavio.HelloWorldResponse)
            Dim inValue As serviciowebFlavio.HelloWorldRequest = New serviciowebFlavio.HelloWorldRequest()
            inValue.Body = New serviciowebFlavio.HelloWorldRequestBody()
            Return CType(Me,serviciowebFlavio.serviciowebSoap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_CrearConsulta(ByVal request As serviciowebFlavio.CrearConsultaRequest) As serviciowebFlavio.CrearConsultaResponse Implements serviciowebFlavio.serviciowebSoap.CrearConsulta
            Return MyBase.Channel.CrearConsulta(request)
        End Function
        
        Public Function CrearConsulta() As System.Xml.Linq.XElement
            Dim inValue As serviciowebFlavio.CrearConsultaRequest = New serviciowebFlavio.CrearConsultaRequest()
            inValue.Body = New serviciowebFlavio.CrearConsultaRequestBody()
            Dim retVal As serviciowebFlavio.CrearConsultaResponse = CType(Me,serviciowebFlavio.serviciowebSoap).CrearConsulta(inValue)
            Return retVal.Body.CrearConsultaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_CrearConsultaAsync(ByVal request As serviciowebFlavio.CrearConsultaRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.CrearConsultaResponse) Implements serviciowebFlavio.serviciowebSoap.CrearConsultaAsync
            Return MyBase.Channel.CrearConsultaAsync(request)
        End Function
        
        Public Function CrearConsultaAsync() As System.Threading.Tasks.Task(Of serviciowebFlavio.CrearConsultaResponse)
            Dim inValue As serviciowebFlavio.CrearConsultaRequest = New serviciowebFlavio.CrearConsultaRequest()
            inValue.Body = New serviciowebFlavio.CrearConsultaRequestBody()
            Return CType(Me,serviciowebFlavio.serviciowebSoap).CrearConsultaAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_SeleccionarUsuario(ByVal request As serviciowebFlavio.SeleccionarUsuarioRequest) As serviciowebFlavio.SeleccionarUsuarioResponse Implements serviciowebFlavio.serviciowebSoap.SeleccionarUsuario
            Return MyBase.Channel.SeleccionarUsuario(request)
        End Function
        
        Public Function SeleccionarUsuario(ByVal id As Integer) As System.Xml.Linq.XElement
            Dim inValue As serviciowebFlavio.SeleccionarUsuarioRequest = New serviciowebFlavio.SeleccionarUsuarioRequest()
            inValue.Body = New serviciowebFlavio.SeleccionarUsuarioRequestBody()
            inValue.Body.id = id
            Dim retVal As serviciowebFlavio.SeleccionarUsuarioResponse = CType(Me,serviciowebFlavio.serviciowebSoap).SeleccionarUsuario(inValue)
            Return retVal.Body.SeleccionarUsuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_SeleccionarUsuarioAsync(ByVal request As serviciowebFlavio.SeleccionarUsuarioRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.SeleccionarUsuarioResponse) Implements serviciowebFlavio.serviciowebSoap.SeleccionarUsuarioAsync
            Return MyBase.Channel.SeleccionarUsuarioAsync(request)
        End Function
        
        Public Function SeleccionarUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of serviciowebFlavio.SeleccionarUsuarioResponse)
            Dim inValue As serviciowebFlavio.SeleccionarUsuarioRequest = New serviciowebFlavio.SeleccionarUsuarioRequest()
            inValue.Body = New serviciowebFlavio.SeleccionarUsuarioRequestBody()
            inValue.Body.id = id
            Return CType(Me,serviciowebFlavio.serviciowebSoap).SeleccionarUsuarioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_crearUsuario(ByVal request As serviciowebFlavio.crearUsuarioRequest) As serviciowebFlavio.crearUsuarioResponse Implements serviciowebFlavio.serviciowebSoap.crearUsuario
            Return MyBase.Channel.crearUsuario(request)
        End Function
        
        Public Function crearUsuario(ByVal nombre As String, ByVal contrasena As String) As System.Xml.Linq.XElement
            Dim inValue As serviciowebFlavio.crearUsuarioRequest = New serviciowebFlavio.crearUsuarioRequest()
            inValue.Body = New serviciowebFlavio.crearUsuarioRequestBody()
            inValue.Body.nombre = nombre
            inValue.Body.contrasena = contrasena
            Dim retVal As serviciowebFlavio.crearUsuarioResponse = CType(Me,serviciowebFlavio.serviciowebSoap).crearUsuario(inValue)
            Return retVal.Body.crearUsuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_crearUsuarioAsync(ByVal request As serviciowebFlavio.crearUsuarioRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.crearUsuarioResponse) Implements serviciowebFlavio.serviciowebSoap.crearUsuarioAsync
            Return MyBase.Channel.crearUsuarioAsync(request)
        End Function
        
        Public Function crearUsuarioAsync(ByVal nombre As String, ByVal contrasena As String) As System.Threading.Tasks.Task(Of serviciowebFlavio.crearUsuarioResponse)
            Dim inValue As serviciowebFlavio.crearUsuarioRequest = New serviciowebFlavio.crearUsuarioRequest()
            inValue.Body = New serviciowebFlavio.crearUsuarioRequestBody()
            inValue.Body.nombre = nombre
            inValue.Body.contrasena = contrasena
            Return CType(Me,serviciowebFlavio.serviciowebSoap).crearUsuarioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_EliminarUsuario(ByVal request As serviciowebFlavio.EliminarUsuarioRequest) As serviciowebFlavio.EliminarUsuarioResponse Implements serviciowebFlavio.serviciowebSoap.EliminarUsuario
            Return MyBase.Channel.EliminarUsuario(request)
        End Function
        
        Public Function EliminarUsuario(ByVal id As Integer) As System.Xml.Linq.XElement
            Dim inValue As serviciowebFlavio.EliminarUsuarioRequest = New serviciowebFlavio.EliminarUsuarioRequest()
            inValue.Body = New serviciowebFlavio.EliminarUsuarioRequestBody()
            inValue.Body.id = id
            Dim retVal As serviciowebFlavio.EliminarUsuarioResponse = CType(Me,serviciowebFlavio.serviciowebSoap).EliminarUsuario(inValue)
            Return retVal.Body.EliminarUsuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function serviciowebFlavio_serviciowebSoap_EliminarUsuarioAsync(ByVal request As serviciowebFlavio.EliminarUsuarioRequest) As System.Threading.Tasks.Task(Of serviciowebFlavio.EliminarUsuarioResponse) Implements serviciowebFlavio.serviciowebSoap.EliminarUsuarioAsync
            Return MyBase.Channel.EliminarUsuarioAsync(request)
        End Function
        
        Public Function EliminarUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of serviciowebFlavio.EliminarUsuarioResponse)
            Dim inValue As serviciowebFlavio.EliminarUsuarioRequest = New serviciowebFlavio.EliminarUsuarioRequest()
            inValue.Body = New serviciowebFlavio.EliminarUsuarioRequestBody()
            inValue.Body.id = id
            Return CType(Me,serviciowebFlavio.serviciowebSoap).EliminarUsuarioAsync(inValue)
        End Function
    End Class
End Namespace
